### ISSUE TITLE
Typo in node_modules/capval/cds-plugin.js which breaks work of custom handlers

### ISSUE THREAD

**Issue by tiosteel** [MertSAP/CAPVAL#15]
Hi @MertSAP 

In the [https://github.com/MertSAP/CAPVAL/blob/main/cds-plugin.js#L60](https://github.com/MertSAP/CAPVAL/blob/main/cds-plugin.js#L60) there is

```
          if (
            entity.isRoot &&
            (entity.HasHandlers || entity.AncestorsHavehandlers)
          ) {
```

It should be
```
          if (
            entity.isRoot &&
            (entity.HasHandlers || entity.AncestorsHaveHandlers) // h -> H
          ) {
```

Currently custom handlers doesn't work because of the typo.

**Comment by MertSAP** [comment]
Fixed. Well spotted. Pushed out v2.0.3. Thanks for using CAPVAL and contributing!

**Comment by MertSAP** [comment]
Closing issue
